batch_size: 256
beta: 3.0
buffer_size: 10000000
checkpoints_path: corl_logs/DPsynthER-walker2d-medium-replay-v2-epsilon_8-seed_0-671f3412
device: cuda
diffusion:
  num_steps: 128
  path: ./results_walker2d-medium-replay-v2/walker2d-medium-replay-v2_samples_5000000.0_8dp.npz
  sample_limit: -1
discount: 0.99
dp_epsilon: 8
env: walker2d-medium-replay-v2
eval_freq: 5000
group: iql-walker2d-medium-replay-v2-multiseed-v0
iql_deterministic: false
iql_tau: 0.7
load_model: ''
log_every: 1000
max_timesteps: 1000000
n_episodes: 10
name: DPsynthER-walker2d-medium-replay-v2-epsilon_8-seed_0-671f3412
network_depth: 2
network_width: 256
normalize: true
normalize_reward: false
project: CORL
save_checkpoints: false
seed: 0
tau: 0.005
