alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: corl_logs/TD3-BC-walker2d-medium-replay-v2-epsilon_0-seed_0-04883f32
device: cuda
diffusion:
  num_steps: 128
  path: null
  sample_limit: -1
discount: 0.99
dp_epsilon: 0
env: walker2d-medium-replay-v2
eval_freq: 5000
expl_noise: 0.1
group: td3-bc-walker2d-medium-replay-v2-multiseed-v0
load_model: ''
log_every: 1000
max_timesteps: 1000000
n_episodes: 10
name: TD3-BC-walker2d-medium-replay-v2-epsilon_0-seed_0-04883f32
network_depth: 2
network_width: 256
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: CORL
save_checkpoints: false
seed: 0
tau: 0.005
