batch_size: 256
beta: 3.0
buffer_size: 10000000
checkpoints_path: corl_logs/DPsynthER-hopper-medium-replay-v2-epsilon_8-seed_0-cafe9f5b
device: cuda
diffusion:
  num_steps: 128
  path: ./results_hopper-medium-replay-v2/hopper-medium-replay-v2_samples_5000000.0_8dp.npz
  sample_limit: -1
discount: 0.99
dp_epsilon: 8
env: hopper-medium-replay-v2
eval_freq: 5000
group: iql-hopper-medium-replay-v2-multiseed-v0
iql_deterministic: true
iql_tau: 0.7
load_model: ''
log_every: 1000
max_timesteps: 1000000
n_episodes: 10
name: DPsynthER-hopper-medium-replay-v2-epsilon_8-seed_0-cafe9f5b
network_depth: 2
network_width: 256
normalize: true
normalize_reward: true
project: CORL
save_checkpoints: false
seed: 0
tau: 0.001
