alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: corl_logs/DPsynthER-halfcheetah-medium-replay-v2-epsilon_10-e03d42d0
device: cuda
diffusion:
  num_steps: 128
  path: ./results_halfcheetah-medium-replay-v2/halfcheetah-medium-replay-v2_samples_5000000.0_10dp.npz
  sample_limit: -1
discount: 0.99
dp_epsilon: 10
env: halfcheetah-medium-replay-v2
eval_freq: 5000
expl_noise: 0.1
group: td3-bc-halfcheetah-medium-replay-v2-multiseed-v0
load_model: ''
log_every: 1000
max_timesteps: 1000000
n_episodes: 10
name: DPsynthER-halfcheetah-medium-replay-v2-epsilon_10-e03d42d0
network_depth: 2
network_width: 256
noise_clip: 0.5
normalize: true
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: CORL
save_checkpoints: false
seed: 0
tau: 0.005
